name = "WebForms"
short_description = """
Demonstrates building simple HTML forms that send submissions into a Bitswan pipeline. Covers field handling, basic validation, and success/error feedback. Great starting point for user-driven inputs.
"""
icon = """
<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="#22c55e" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect x="3" y="4" width="18" height="16" rx="2"/><path d="M7 8h10M7 12h6M7 16h4"/></svg>
"""


