name = "ProtectedWebForm"
short_description = """
Provides a password-protected web form for submitting data to the pipeline. Suitable for internal tools and admin-only inputs.
"""
icon = """
<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="#6366f1" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M12 2l7 4v6c0 5-3.5 9-7 10-3.5-1-7-5-7-10V6z"/></svg>
"""


