name: Build and Push Docker Image

on:
  push:
    branches: [ master ]
    
jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repo
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

    - name: Get Year and Commit Hash
      id: vars
      run: |
        echo "::set-output name=year::$(date +%Y)"
        echo "::set-output name=commit_hash::$(git rev-parse --short HEAD)"

    - name: Build and push Docker images
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: |
          $DOCKER_REGISTRY/$DOCKER_IMAGE:latest
          $DOCKER_REGISTRY/$DOCKER_IMAGE:${{ steps.vars.outputs.year }}-${{ github.run_id }}-git-${{ steps.vars.outputs.commit_hash }}
          $DOCKER_REGISTRY/$DOCKER_IMAGE:$(docker images --no-trunc -q $DOCKER_REGISTRY/$DOCKER_IMAGE:latest | sed 's/:/_/g')


