name: Deploy MkDocs Documentation via FTPS

on:
  push:
    branches: [ main, mkdocs ]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./doc

    steps:
      - name: Checkout repository # Step 1: Get your code from GitHub
        uses: actions/checkout@v4

      - name: Set up Python # Step 2: Install Python, required for MkDocs
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' # Use a specific version like '3.9' or '3.10'

      - name: Install MkDocs and dependencies # Step 3: Install MkDocs and your chosen theme/plugins
        run: pip install mkdocs mkdocs-material mkdocstrings mkdocstrings-python pymdown-extensions

      - name: Build MkDocs site # Step 4: Generate the static HTML/CSS/JS files
        run: mkdocs build

      - name: Deploy MkDocs to Server via FTPS # Step 5: Upload the built site using FTP/FTPS
        uses: SamKirkland/FTP-Deploy-Action@v4.3.0
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASS }}
          port: 21
          protocol: ftps
          local-dir: site/
          server-dir: /
          delete: true # This option deletes files on the server that are not present in your local-dir.
          insecure: true
