name: Deploy Sphinx Documentation via FTPS

on:
  push:
    branches: [ main ]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    container:
      image: python:3.13

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          apt-get update
          apt-get -y install unixodbc-dev

      - name: Configure git safe directory
        run: |
          git config --global --add safe.directory /__w/BitSwan/BitSwan

      - name: Install Python dependencies
        run: |
          pip3 install --upgrade cython
          pip3 install .[dev]
          pip3 install -r doc/requirements.txt

      - name: Build Sphinx documentation
        run: |
          cd ./doc
          make html

      - name: Deploy via FTP
        uses: sebastianpopp/ftp-action@releases/v2
        with:
          host: ${{ secrets.FTP_HOST }}
          user: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASS }}
          localDir: "./doc/_build/html/"
          remoteDir: "/"
          options: "--delete --transfer-all --verbose --no-perms"
