name: Python 3.10 Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    container:
      image: python:3.10

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        apt-get update
        apt-get -y install unixodbc-dev
        git config --global --add safe.directory /__w/BitSwan/BitSwan
        pip3 install --upgrade cython
        pip3 install .[dev]

    - name: Run tests
      run: |
        pytest bspump/file

    - name: Run bitswan tests
      run: |
        bitswan-cli --test examples/Testing/main.ipynb
        bitswan-cli --test examples/Testing/MultiplePipelines/main.ipynb
        bitswan-cli --test examples/Testing/AutoPipeline/main.ipynb


    - name: Run linter
      run: |
        black --check bspump
        ruff check bspump
